---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: networking-oss-deployments
  - name: networking-oss-tools
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/add-credhub-value/task

params:
  ENVIRONMENT:
  NAME:
  VALUE:
