---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: deployments-routing
- name: cf-release-tarball
- name: cf-release
- name: routing-release
- name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/deploy-cf-to-bosh-lite/gcp_task

params:
  CF_RELEASE_TARBALL_DIR: cf-release-tarball
  CF_RELEASE_DIR: cf-release
  ENVIRONMENT:
