---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: networking-oss-deployments
- name: routing-release
- name: routing-release-ci

outputs:
  - name: cipher-manifest

run:
  path: routing-release-ci/ci/tasks/generate-cipher-manifest/task

params:
  CIPHERS:
  OUTPUT_DIR: cipher-manifest
  ENVIRONMENT:
