---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
  - name: mysql-release-source
  - name: routing-release-ci

outputs:
  - name: mysql-manifest

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT: ~
  BOSH_TARGET: ~
  BOSH_USER: ~
  BOSH_PASSWORD: ~

run:
  path: routing-release-ci/ci/tasks/mysql/generate_mysql_manifest
