---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/tas-runtime-deploy

inputs:
  - name: routing-release-ci
  - name: networking-oss-deployments
    optional: true
  - name: toolsmiths-metadata-dir
    optional: true
  - name: cf-deployment-concourse-tasks

outputs:
  - name: created-integration-configs

run:
  path: routing-release-ci/ci/tasks/create-integration-configs/task

params:
  ISO_SEG_NAME:
  ISO_SEG_DOMAIN_PREFIX: iso-seg
  ENABLE_ISOLATION_SEGMENT_TESTS: true
  ENABLE_DYNAMIC_ASG_TESTS: true
  ENVIRONMENT:
  GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  GIT_COMMIT_USERNAME: "CI Bot"
