---
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

platform: linux

inputs:
  - name: routing-release-ci
  - name: master-release

outputs:
  - name: release-notes

run:
  path: routing-release-ci/ci/tasks/build-release-notes/task

params:
  SOURCE_DIR: master-release
  OUTPUT_DIR: release-notes
