iaas_settings:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  subnet_configs:
    - name: router1
      type: manual
      subnets:
      - cloud_properties: {}
        range: 10.244.14.0/30
        reserved:
        - 10.244.14.1
        static:
        - 10.244.14.2
      - cloud_properties: {}
        range: 10.244.14.4/30
        reserved:
        - 10.244.14.5
        static:
        - 10.244.14.6
      - cloud_properties: {}
        range: 10.244.14.8/30
        reserved:
        - 10.244.14.9
        static:
        - 10.244.14.10
      - cloud_properties: {}
        range: 10.244.14.12/30
        reserved:
        - 10.244.14.13
        static: []
      - cloud_properties: {}
        range: 10.244.14.16/30
        reserved:
        - 10.244.14.17
        static: []
      - cloud_properties: {}
        range: 10.244.14.20/30
        reserved:
        - 10.244.14.21
        static: []
      - cloud_properties: {}
        range: 10.244.14.24/30
        reserved:
        - 10.244.14.25
        static: []
      - cloud_properties: {}
        range: 10.244.14.28/30
        reserved:
        - 10.244.14.29
        static: []
      - cloud_properties: {}
        range: 10.244.14.32/30
        reserved:
        - 10.244.14.33
        static: []
      - cloud_properties: {}
        range: 10.244.14.36/30
        reserved:
        - 10.244.14.37
        static: []
    - name: router2
      type: manual
      subnets:
      - cloud_properties: {}
        range: 10.244.10.0/30
        reserved:
        - 10.244.10.1
        static:
        - 10.244.10.2
      - cloud_properties: {}
        range: 10.244.10.4/30
        reserved:
        - 10.244.10.5
        static:
        - 10.244.10.6
      - cloud_properties: {}
        range: 10.244.10.8/30
        reserved:
        - 10.244.10.9
        static:
        - 10.244.10.10
      - cloud_properties: {}
        range: 10.244.10.12/30
        reserved:
        - 10.244.10.13
        static: []
      - cloud_properties: {}
        range: 10.244.10.16/30
        reserved:
        - 10.244.10.17
        static: []
      - cloud_properties: {}
        range: 10.244.10.20/30
        reserved:
        - 10.244.10.21
        static: []
      - cloud_properties: {}
        range: 10.244.10.24/30
        reserved:
        - 10.244.10.25
        static: []
    - name: router3
      type: manual
      subnets:
      - cloud_properties: {}
        range: 10.244.12.0/30
        reserved:
        - 10.244.12.1
        static:
        - 10.244.12.2
      - cloud_properties: {}
        range: 10.244.12.4/30
        reserved:
        - 10.244.12.5
        static:
        - 10.244.12.6
      - cloud_properties: {}
        range: 10.244.12.8/30
        reserved:
        - 10.244.12.9
        static:
        - 10.244.12.10
      - cloud_properties: {}
        range: 10.244.12.12/30
        reserved:
        - 10.244.12.13
        static: []
      - cloud_properties: {}
        range: 10.244.12.16/30
        reserved:
        - 10.244.12.17
        static: []
      - cloud_properties: {}
        range: 10.244.12.20/30
        reserved:
        - 10.244.12.21
        static: []
      - cloud_properties: {}
        range: 10.244.12.24/30
        reserved:
        - 10.244.12.25
        static: []

  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: routing_api_z1
      cloud_properties: {}
    - name: routing_api_z2
      cloud_properties: {}
    - name: routing_api_z3
      cloud_properties: {}
    - name: tcp_router_z1
      cloud_properties: {}
    - name: tcp_router_z2
      cloud_properties: {}
    - name: tcp_router_z3
      cloud_properties: {}
    - name: tcp_emitter_z1
      cloud_properties: {}
    - name: tcp_emitter_z2
      cloud_properties: {}
    - name: tcp_emitter_z3
      cloud_properties: {}
    - name: small_errand
      cloud_properties: {}
