---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: submodule-latest
- name: needs-bump
- name: routing-release-ci

outputs:
- name: bumped

run:
  path: routing-release-ci/ci/tasks/bump-submodule/task

params:
  # relative path of the submodule within needs-bump input
  SUBMODULE_PATH: ~

  # name of branch in the top-level repo on which to commit the submodule bump
  BRANCH: master

  # Identity to use for the git commit
  GIT_COMMIT_USERNAME: "CF Routing Team CI Bot"
  GIT_COMMIT_EMAIL: "cf-routing-eng@pivotal.io"
