---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-deploy

inputs:
- name: release
- name: package-release
- name: routing-release-ci

outputs:
- name: modified-release

params:
  RELEASE: routing-release
  PACKAGE:
  BRANCH: develop
  GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:

  # Identity to use for the git commit
  GIT_COMMIT_USERNAME: "CF Networking Team CI Bot"
  GIT_COMMIT_EMAIL: "cf-networking@pivotal.io"

run:
  path: routing-release-ci/ci/tasks/upgrade-package-in-release/task
