---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/tas-runtime-thin

inputs:
  - name: routing-release-ci
  - name: networking-oss-deployments

outputs:
  - name: created-drats-config

params:
  ENVIRONMENT:
  ENV_PATH:
  GIT_COMMIT_EMAIL: cf-routing-eng@pivotal.io
  GIT_COMMIT_USERNAME: "CI Bot"

run:
  path: routing-release-ci/ci/tasks/create-drats-config/task
