---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: networking-oss-deployments
    optional: true
  - name: toolsmiths-metadata-dir
    optional: true
  - name: routing-release-ci
  - name: indicator-protocol-release

run:
  path: routing-release-ci/ci/tasks/indicator-protocol-test/task

params:
  ENVIRONMENT:
