---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: release-dir
  - name: deployments-routing
  - name: routing-release-ci

outputs:
  - name: release-tarball

run:
  path: routing-release-ci/ci/tasks/create-release-tarball/task

params:
  RELEASE_DIR: release-dir
