platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: cf-routing-release-develop
  - name: deployments-routing
  - name: cf-routing-release-master
  - name: routing-release-ci

outputs:
  - name: cf-routing-release-mergedmaster

run:
  path: routing-release-ci/ci/tasks/merge-routing-release-master-into-develop/task
