haproxy/haproxy-2.7.6.tar.gz:
  size: 4162978
  object_id: 7ae15149-20bc-4d0e-4691-0491f57f35b4
  sha: sha256:133f357ddb3fcfc5ad8149ef3d74cbb5db6bb4a5ab67289ce0b0ab686cdeb74f
jq/jq-1.6-linux64.tgz:
  size: 1708805
  object_id: cb77c7f7-d8d5-45d5-6117-f49a92bafb1f
  sha: sha256:2074c8209a0eebe4b9c02be3c405614b475b1bd84fbbb1ca76135f7d0cfcc009
