---
haproxy/haproxy-1.5.12.tar.gz:
  object_id: 59097996-16c1-4f42-9188-0d59cbfbc139
  sha: c488f7f108ddefb558bd86e7cbc1b71636ada856
  size: 1344813
haproxy/pcre-8.37.tar.gz:
  object_id: 038b1b6f-d7be-4b0d-9260-b2cfc0597480
  sha: 4a24a20c61347d8da4edc86d5475aaf70ac146bb
  size: 2041593
rtr/rtr-linux-amd64.tgz:
  object_id: 4a131d23-7f4f-4811-88cb-c6401171b11d
  sha: 4d39d58a8dae9ed8505955e6811176af0fc86005
  size: 2593243
cf-cli/cf-linux-amd64.tgz:
  object_id: f4197c67-fff8-4762-94a8-8f5cf6413448
  sha: ad1782a564c5bf47270e1bfbe0fdd1298394a1d0
  size: 6104120
golang/go1.5.4.linux-amd64.tar.gz:
  object_id: feb6479c-00d3-4d0c-bec6-3fdb7808b304
  sha: 4c919c3390e86e557a8019ea644e835bc493be2a
  size: 80180116
