---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: istio-release
- name: routing-release-ci
- name: envoy-tarball

outputs:
- name: updated-istio-release

run:
  path: routing-release-ci/ci/tasks/envoy-blob/update/task

params:
  GCP_BLOBSTORE_SERVICE_ACCOUNT_KEY:
