---
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/tas-runtime-thin

platform: linux

inputs:
  - name: routing-release-ci
  - name: master-release

run:
  path: routing-release-ci/ci/tasks/print-bosh-job-spec-diff/task

params:
  SOURCE_DIR: master-release
