config_from_cf:
  cf_deployment_name: (( name ))
  consul:
    log_level: (( properties.consul.agent.log_level ))
    lan_servers: (( properties.consul.agent.servers.lan ))
    ca_cert: (( properties.consul.ca_cert ))
    agent_cert: (( properties.consul.agent_cert ))
    agent_key: (( properties.consul.agent_key ))
    encrypt_keys: (( properties.consul.encrypt_keys ))
    require_ssl: (( properties.consul.require_ssl ))
    server_cert: (( properties.consul.server_cert ))
    server_key: (( properties.consul.server_key ))
  loggregator:
    etcd_machines: (( properties.loggregator.etcd.machines ))
  etcd:
    machines: (( properties.etcd.machines ))
  metron_endpoint:
    shared_secret: (( properties.metron_endpoint.shared_secret ))
  system_domain: (( properties.system_domain ))
  uaa:
    port: (( properties.uaa.port ))
    ssl:
      port: (( properties.uaa.ssl.port ))
    clients:
      gorouter:
        secret: (( properties.uaa.clients.gorouter.secret ))
      tcp_emitter:
        secret: (( properties.uaa.clients.tcp_emitter.secret ))
      tcp_router:
        secret: (( properties.uaa.clients.tcp_router.secret ))

# The keys below should not be included in the final stub
name: (( merge ))
properties:
  system_domain: (( merge ))
  consul:
    agent:
      log_level: (( merge ))
      servers:
        lan: (( merge ))
    ca_cert:
    agent_cert:
    agent_key:
    encrypt_keys:
    require_ssl:
    server_cert:
    server_key:
  loggregator:
    etcd:
      machines: (( merge ))
  etcd:
    machines: (( merge ))
  metron_endpoint:
    shared_secret: (( merge ))
  uaa:
    port:
    ssl:
      port:
    clients:
      gorouter:
        secret:
      tcp_emitter:
        secret:
      tcp_router:
        secret:
