config_from_cf:
  acceptance_tests:
    apps_domain: (( merge ))
    api: (( merge ))
    admin_user: (( merge ))
    admin_password: (( merge ))
    skip_ssl_validation: (( merge ))
    use_http: (( merge ))
  cf_deployment_name: (( merge ))
  system_domain: (( merge ))
  consul:
    domain: (( merge ))
    log_level: (( merge ))
    lan_servers: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    require_ssl: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))
  loggregator:
    etcd_machines: (( merge ))
  metron_endpoint:
    shared_secret: (( merge ))
  etcd:
    machines: (( merge ))
  uaa:
    port: (( merge ))
    ssl:
      port: (( merge ))
    clients:
      gorouter:
        secret: (( merge ))
      tcp_emitter:
        secret: (( merge ))
      tcp_router:
        secret: (( merge ))
