---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: deployments-routing
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/setup-cf-env/task

params:
  CF_ADMIN_PASSWORD:
  CF_ADMIN_USER: admin
  CF_ORG:
  CF_PASSWORD:
  CF_SKIP_SSL_VALIDATION: true
  CF_SPACE:
  CF_SPACE_ROLE: SpaceDeveloper
  CF_USERNAME:
  ENVIRONMENT:
  SYSTEM_DOMAIN:
