# this task downloads a specific version of the envoy docker image
# extracts the binary and generates a tarball from it
#
---
platform: linux

# task must run with privileged: true
# see: https://github.com/concourse/docker-image-resource/issues/164

image_resource:
  type: docker-image
  source:
    # a hack so that we can 'docker pull' from inside the task
    repository: concourse/docker-image-resource

params:
  DOCKER_REPO: envoyproxy/envoy

inputs:
- name: routing-release-ci

  # will pull the envoy docker image matching this version of the source code
- name: envoy-source

outputs:
  # will drop envoy.tgz and version file into this directory
- name: envoy-tarball

run:
  path: routing-release-ci/ci/tasks/envoy-blob/pull-from-docker/task
