---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: routing-release-ci
- name: release-repo
- name: release-repo-master

outputs:
- name: final-release-repo

run:
  path: routing-release-ci/ci/tasks/merge-nats-release-master-into-develop/task

params:
  MASTER_BRANCH:
  MERGED_REPO: final-release-repo
  MERGE_MESSAGE:
