---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-jupyter

inputs:
  - name: routing-release-master
  - name: routing-release-rc
  - name: routing-perf-release
  - name: rc-csv-dir
  - name: master-csv-dir
  - name: rc-version
  - name: final-version
  - name: routing-release-ci

outputs:
  - name: final-comparison-report
  - name: rc-comparison-report

run:
  path: routing-release-ci/ci/tasks/create-performance-comparison-report/task
