---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: bbl-state
- name: nats-release
- name: routing-release-ci
- name: stemcell
- name: cf-deployment-concourse-tasks

run:
  path: routing-release-ci/ci/tasks/bosh-deploy-nats/task

params:
  BBL_STATE_DIR: bbl-state
